package com.gonulyavuz;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.*;
import java.io.Console;

public class Main {

    public static void main(String[] args) throws IOException {
        // Scenario #1
        // Dates generated by http://www.timestampgenerator.com/
        System.out.println("Playing out Scenario #1...");

        Event paperDate = new Event("Paper Date", new Date(118, 6, 16, 9, 0));
        Event basketball_match = new Event("Basketball Match", new Date(118,6,17,9,0));
        Event conferenceDinner = new Event("Conference Dinner", new Date(118,6,20,18,0));
        ServiceAgent masConference = new ServiceAgent("MAS18", new HashSet<Event>() {{
            // 16 July 2018
            add(paperDate);

            // 20 July 2018
            add(conferenceDinner);
        }});

        ServiceAgent eventful = new ServiceAgent("amsterdam.eventful", new HashSet<Event>() {{
            // 16 July 2018
            add(new Event("Art Gallery", new Date(118,6,16,9,0)));
            add(new Event("Festival", new Date(118,6,16,18,0)));
            add(new Event("Concert", new Date(118,6,16,18,0)));

            // 17 July 2018
            add(new Event("Campus Tour", new Date(118,6,17,9,0)));
            add(basketball_match);
            add(new Event("Cinema", new Date(118,6,17,9,0)));

            // 18 July 2018
            add(new Event("Museum Tour", new Date(118,6,18,9,0)));

            // 19 July 2018
            add(new Event("Bicycle Tour in Vondelpark", new Date(118,6,19,18,0)));
            add(new Event("Theatre", new Date(118,6,19,18,0)));

            // 20 July 2018
            add(new Event("Bicycle Tour in Vondelpark", new Date(118,6,20,9,0)));
        }});

        ServiceAgent friendA = new ServiceAgent("Takeshi", new HashSet<Event>() {{
            // 21 July 2018
            add(new Event("Shopping", new Date(118,6,21,9,0)));
        }});

        ServiceAgent girlfriend = new ServiceAgent("Julia", new HashSet<Event>() {{
            // 17 July 2018
            add(new Event("Cinema", new Date(118,6,17,9,0)));

            // 18 July 2018
            add(new Event("Trekking", new Date(118,6,18,9,0)));
        }});

        List<Desire> initialDesires = new ArrayList<>();
        initialDesires.add(new Desire(0,"Present the paper", new HashSet<ServiceAgent>() {{
            add(masConference);
        }}));
        initialDesires.add(new Desire(1,"Attend Conference Dinner", new HashSet<ServiceAgent>() {{
            add(masConference);
        }}));
        initialDesires.add(new Desire(2,"Go to concert theatre festival", new HashSet<ServiceAgent>() {{
            add(eventful);
        }}));
        initialDesires.add(new Desire(3,"Go to art museum stuff", new HashSet<ServiceAgent>() {{
            add(eventful);
        }}));
        initialDesires.add(new Desire(4,"Go to basketball bicycle activities", new HashSet<ServiceAgent>() {{
            add(eventful);
        }}));
        initialDesires.add(new Desire(5,"NOT have free time", new HashSet<ServiceAgent>() {{
            add(masConference);
        }}));
        initialDesires.add(new Desire(6,"Do shopping", new HashSet<ServiceAgent>() {{
            add(friendA);
        }}));

        Date currentDate = new Date(118, 6, 16, 9, 0);
        BDIAgent tsubasa = new BDIAgent("Tsubasa", initialDesires, currentDate);

        printSummary(tsubasa, currentDate);

        masConference.warnAlter(tsubasa, paperDate, new Date(118,6,19,9,0));

        printSummary(tsubasa, currentDate);

        currentDate = new Date(118, 6, 16, 18, 0);
        tsubasa.setCurrentDateBelief(currentDate);

        tsubasa.addDesire(new Desire(4, "Go to cinema trekking with girlfriend", new HashSet<ServiceAgent>() {{
            add(girlfriend);
        }}));
        tsubasa.constructBeliefs();
        tsubasa.constructIntentions();

        printSummary(tsubasa, currentDate);

        masConference.warnCancel(tsubasa, conferenceDinner);

        for (int date = 17; date <= 21; date++) {
            currentDate = new Date(118, 6, date, 9, 0);
            tsubasa.setCurrentDateBelief(currentDate);
            tsubasa.constructBeliefs();
            tsubasa.constructIntentions();

            printSummary(tsubasa, currentDate);

            currentDate = new Date(118, 6, date, 18, 0);
            tsubasa.setCurrentDateBelief(currentDate);
            tsubasa.constructBeliefs();
            tsubasa.constructIntentions();

            printSummary(tsubasa, currentDate);
        }
    }

    private static void printSummary(BDIAgent agent, Date currentDate) throws IOException {
        System.out.println();
        agent.printBeliefs();
        System.out.println();
        agent.printExpectedIntentions(currentDate);
        System.out.println();
        agent.printCompletedIntentions(currentDate);
        System.out.println();
        agent.printUtilityCalculations(currentDate);

        System.out.println();
        System.out.println("NOW = " + currentDate);

        //new Scanner(System.in).nextLine();
        System.in.read();
    }
}
